# Generated by Django 4.2.1 on 2023-06-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quienesSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primerBloqueTexto', models.CharField(max_length=1000)),
                ('SegundoBloqueTexto', models.CharField(max_length=1000)),
                ('imagenprimerBloqueTexto', models.ImageField(blank=True, null=True, upload_to='quienesSomos/imagenes')),
            ],
        ),
    ]
