# Generated by Django 4.2.1 on 2023-06-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0002_quienessomos_imagensegundobloquetexto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quienessomos',
            name='imagenSegundoBloqueTexto',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes'),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='imagenprimerBloqueTexto',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes'),
        ),
    ]
