# Generated by Django 4.2.1 on 2023-06-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0003_alter_quienessomos_imagensegundobloquetexto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quienessomos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
