# Generated by Django 4.2.1 on 2023-06-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0004_alter_quienessomos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quienessomos',
            options={'verbose_name': 'QuienesSomos', 'verbose_name_plural': 'QuienesSomoss'},
        ),
    ]
