# Generated by Django 4.2.1 on 2023-06-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0005_alter_quienessomos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quienessomos',
            name='SegundoBloqueTexto',
            field=models.CharField(max_length=1500),
        ),
    ]
