# Generated by Django 4.2.1 on 2023-06-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0006_alter_quienessomos_segundobloquetexto'),
    ]

    operations = [
        migrations.AddField(
            model_name='quienessomos',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='imagen5',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='imagen6',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='imagen7',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='imagen8',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes'),
        ),
    ]
