# Generated by Django 4.2.1 on 2023-06-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0007_quienessomos_imagen1_quienessomos_imagen2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.CharField(max_length=1000)),
                ('servicioQueIncluye', models.CharField(max_length=1000)),
                ('minimoDePersonas', models.CharField(max_length=1000)),
                ('puntoDePartida', models.CharField(max_length=1000)),
                ('Informacion', models.CharField(max_length=2000)),
                ('alerta', models.CharField(max_length=1000)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='Imagenes')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='Imagenes')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='Imagenes')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='Imagenes')),
                ('imagen5', models.ImageField(blank=True, null=True, upload_to='Imagenes')),
                ('imagen6', models.ImageField(blank=True, null=True, upload_to='Imagenes')),
                ('imagen7', models.ImageField(blank=True, null=True, upload_to='Imagenes')),
                ('imagen8', models.ImageField(blank=True, null=True, upload_to='Imagenes')),
            ],
            options={
                'verbose_name': 'Excursion1s',
                'verbose_name_plural': 'Excursion1ss',
            },
        ),
    ]
