# Generated by Django 4.2.1 on 2023-06-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0008_excursion1'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion1',
            name='imagenCarrusel1',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes'),
        ),
        migrations.AddField(
            model_name='excursion1',
            name='imagenCarrusel2',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes'),
        ),
        migrations.AddField(
            model_name='excursion1',
            name='imagenCarrusel3',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes'),
        ),
        migrations.AddField(
            model_name='excursion1',
            name='imagenCarrusel4',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes'),
        ),
        migrations.AddField(
            model_name='excursion1',
            name='imagenCarrusel5',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes'),
        ),
    ]
