# Generated by Django 4.2.1 on 2023-06-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0009_excursion1_imagencarrusel1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion1',
            name='nombreDeLaExcursion',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
