# Generated by Django 4.2.1 on 2023-06-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0013_alter_excursion1_informacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion1',
            name='Informacion',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='excursion2',
            name='Informacion',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='excursion3',
            name='Informacion',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='excursion4',
            name='Informacion',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='excursion5',
            name='Informacion',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='excursion6',
            name='Informacion',
            field=models.CharField(max_length=10000),
        ),
    ]
