# Generated by Django 4.2.1 on 2023-06-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0015_alter_excursion2_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursion2',
            options={'verbose_name': 'Excursion2s', 'verbose_name_plural': 'Excursion2ss'},
        ),
        migrations.RemoveConstraint(
            model_name='excursion2',
            name='unique_excursion2',
        ),
        migrations.AlterField(
            model_name='excursion2',
            name='Informacion',
            field=models.CharField(max_length=10000),
        ),
    ]
