# Generated by Django 4.2.1 on 2023-06-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0017_sabiasq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursion2',
            options={},
        ),
        migrations.AlterField(
            model_name='excursion2',
            name='Informacion',
            field=models.CharField(max_length=2000),
        ),
    ]
