# Generated by Django 4.2.1 on 2023-06-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0019_casas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casas',
            options={'verbose_name': 'Casas', 'verbose_name_plural': 'Casas'},
        ),
        migrations.AlterField(
            model_name='casas',
            name='provincia',
            field=models.CharField(choices=[('Habana', 'Habana'), ('Pinar del Rio', 'Pinar del Rio'), ('Matanzas', 'Matanzas'), ('Ciuenfuegos', 'Ciuenfuegos')], max_length=50, null=True),
        ),
    ]
