# Generated by Django 4.2.1 on 2023-06-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0021_casas_nombrecasa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casas',
            options={'verbose_name': 'Casas', 'verbose_name_plural': 'Casass'},
        ),
        migrations.RemoveField(
            model_name='casas',
            name='imagen1',
        ),
    ]
