# Generated by Django 4.2.1 on 2023-06-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0022_alter_casas_options_remove_casas_imagen1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(choices=[('Habana', 'Habana'), ('Pinar del Rio', 'Pinar del Rio'), ('Matanzas', 'Matanzas'), ('Ciuenfuegos', 'Ciuenfuegos')], max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='casas',
            name='provincia',
        ),
        migrations.AddField(
            model_name='casas',
            name='provincias',
            field=models.ManyToManyField(related_name='producto_subcat', to='TodaCubaApp.provincia'),
        ),
    ]
