# Generated by Django 4.2.1 on 2023-06-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0023_provincia_remove_casas_provincia_casas_provincias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'Provincias', 'verbose_name_plural': 'Provinciass'},
        ),
        migrations.AlterField(
            model_name='provincia',
            name='provincia',
            field=models.CharField(choices=[('Habana', 'Habana'), ('Pinar del Rio', 'Pinar del Rio'), ('Matanzas', 'Matanzas'), ('Ciuenfuegos', 'Cienfuegos')], max_length=50, null=True),
        ),
    ]
