# Generated by Django 4.2.1 on 2023-06-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0024_alter_provincia_options_alter_provincia_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='provincia',
            field=models.CharField(choices=[('Habana', 'Habana'), ('Pinar del Rio', 'Pinar del Rio'), ('Matanzas', 'Matanzas'), ('Cienfuegos', 'Cienfuegos')], max_length=50, null=True),
        ),
    ]
