# Generated by Django 4.2.1 on 2023-07-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0025_alter_provincia_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quienessomos',
            name='primerBloqueTexto',
            field=models.CharField(max_length=2000),
        ),
    ]
