# Generated by Django 4.2.1 on 2023-07-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0026_alter_quienessomos_primerbloquetexto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursion1',
            options={},
        ),
    ]
