# Generated by Django 4.2.1 on 2023-07-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0027_alter_excursion1_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='provincia',
            field=models.CharField(choices=[('Habana', 'Habana'), ('Pinar del Rio', 'Pinar del Rio'), ('Matanzas', 'Matanzas'), ('Cienfuegos', 'Cienfuegos'), ('Artemisa', 'Artemisa'), ('Mayabeque', 'Mayabeque'), ('Villa Clara', 'Villa Clara'), ('Las Tunas', 'Las Tunas'), ('Granma', 'Granma'), ('Holguin', 'Holguin'), ('Guantánamo', 'Guantánamo'), ('Santiago de Cuba', 'Santiago de Cuba'), ('Sancti Spíritus', 'Sancti Spíritus'), ('Ciego de Ávila', 'Ciego de Ávila'), ('Isla de la Juventud', 'Isla de la Juventud')], max_length=50, null=True),
        ),
    ]
