# Generated by Django 4.2.1 on 2023-07-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodaCubaApp', '0028_alter_provincia_provincia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
    ]
